version: '3.5'

services:
    nginx:
        container_name: showtimegram-nginx
        image: nginx
        ports:
        - 8080:80
        volumes:
        - ./:/app
        - ./docker/etc/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - php
        restart: always
    php:
        container_name: showtimegram-php
        build:
            context: ./docker/php
        environment:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        expose:
        - 9001
        volumes:
        - ./:/app
        - ./docker/etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        working_dir: /app
